name: Tests

on: push
  # - pull_request

jobs:
  test:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2.15
      with:
        node-version: '14.x'
    - name: Install dependencies 
      run: yarn
    - name: Run tests
      run: yarn test